root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
full_bin = "DEBUG=true DATALEAKS_FOLDERS=../testdata ./tmp/main"
args = []
exclude_dir = ["tmp", "vendor"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
send_interrupt = false
delay = 1000 # ms
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
